update pre-upgrade

diff --git a/charts/testkube/templates/pre-upgrade.yaml b/charts/testkube/templates/pre-upgrade.yaml
--- a/charts/testkube/templates/pre-upgrade.yaml
+++ b/charts/testkube/templates/pre-upgrade.yaml
@@ -34,9 +34,18 @@ spec:
             echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list;
             apt-get update;
             apt install mongodb-org-tools -y;
+
             echo "Starting MongoDB Backup";
             NOW="$(date +"%F")-$(date +"%T")";
             FILE="mongodb_dump-$NOW";
             mongodump --uri=mongodb://testkube-mongodb:27017  --out=/mongodump/db/$FILE;
+            kubectl scale deployment testkube-mongodb --replicas=0 -n testkube;
+            sleep 2;
+            kubectl delete pvc testkube-mongodb -n testkube || echo "MongoDB volume not found. Continuing with creating a new one";
+
+            echo "Waiting for a new MongoDB volume to spin up";
+            sleep 20;
+            mongorestore --uri=mongodb://testkube-mongodb:27017 --db=testkube /mongodump/db/$FILE;
             else echo "MongoDB is up-to-date"; fi
+
       restartPolicy: Never
