Testkube tests - WIP

diff --git a/.github/workflows/helm-deploy-testkube-charts-stage.yaml b/.github/workflows/helm-deploy-testkube-charts-stage.yaml
--- a/.github/workflows/helm-deploy-testkube-charts-stage.yaml
+++ b/.github/workflows/helm-deploy-testkube-charts-stage.yaml
@@ -2,15 +2,19 @@ name: Releasing Testkube Helm charts to Stage k8s Cluster.
 
 concurrency: staging_cluster
 
+# on:
+#   repository_dispatch:
+#     types:
+#       [
+#         trigger-workflow,
+#         trigger-workflow-dashboard,
+#         trigger-workflow-operator,
+#         trigger-workflow-executor,
+#       ]
+
 on:
-  repository_dispatch:
-    types:
-      [
-        trigger-workflow,
-        trigger-workflow-dashboard,
-        trigger-workflow-operator,
-        trigger-workflow-executor,
-      ]
+  pull_request:
+# TODO: remove - just for woflow tests
 
 env:
   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
@@ -22,117 +26,117 @@ env:
   POSTMAN_TEST_FILE_PATH: test/postman
 
 jobs:
-  release_charts_if_image_updated:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.client_payload.ref }}
+  # release_charts_if_image_updated:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: ${{ github.event.client_payload.ref }}
 
-      - name: Configure Git
-        run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+  #     - name: Configure Git
+  #       run: |
+  #         git config user.name "$GITHUB_ACTOR"
+  #         git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
 
-      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
-        with:
-          service_account_key: ${{ secrets.GKE_SA_KEY }}
-          project_id: ${{ secrets.GKE_PROJECT }}
-      - run: |-
-          gcloud --quiet auth configure-docker
+  #     - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
+  #       with:
+  #         service_account_key: ${{ secrets.GKE_SA_KEY }}
+  #         project_id: ${{ secrets.GKE_PROJECT }}
+  #     - run: |-
+  #         gcloud --quiet auth configure-docker
 
-      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
-        with:
-          cluster_name: ${{ env.GKE_CLUSTER_NAME_STAGE }}
-          location: ${{ env.GKE_ZONE_STAGE }}
-          credentials: ${{ secrets.GKE_SA_KEY }}
+  #     - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
+  #       with:
+  #         cluster_name: ${{ env.GKE_CLUSTER_NAME_STAGE }}
+  #         location: ${{ env.GKE_ZONE_STAGE }}
+  #         credentials: ${{ secrets.GKE_SA_KEY }}
 
-      - name: Install Helm
-        uses: azure/setup-helm@v1
-        with:
-          version: v3.4.0
+  #     - name: Install Helm
+  #       uses: azure/setup-helm@v1
+  #       with:
+  #         version: v3.4.0
 
-      - name: Modify executors.json file if any executor Docker image was updated
-        if: ${{ github.event.client_payload.image_tag_executor }}
-        run: |
-          export image_tag=${{ github.event.client_payload.image_tag_executor }}
-          export executor_name=${{ github.event.client_payload.executor_name }}
-          sed -i "s/\(.*\"image\":.*$executor_name.*\:\).*$/\1$image_tag\",/g" ./charts/testkube-api/executors.json
-          cat ./charts/testkube-api/executors.json
+  #     - name: Modify executors.json file if any executor Docker image was updated
+  #       if: ${{ github.event.client_payload.image_tag_executor }}
+  #       run: |
+  #         export image_tag=${{ github.event.client_payload.image_tag_executor }}
+  #         export executor_name=${{ github.event.client_payload.executor_name }}
+  #         sed -i "s/\(.*\"image\":.*$executor_name.*\:\).*$/\1$image_tag\",/g" ./charts/testkube-api/executors.json
+  #         cat ./charts/testkube-api/executors.json
 
-      - name: Installing repositories
-        run: |
-          helm repo add bitnami https://charts.bitnami.com/bitnami
+  #     - name: Installing repositories
+  #       run: |
+  #         helm repo add bitnami https://charts.bitnami.com/bitnami
 
-      - name: Get image tag of Testkube APi, Dashboard, Operator
-        id: vars
-        run: |
-          echo ::set-output name=api_image_tag::$(kubectl get deployment testkube-api-server -o=jsonpath='{$.spec.template.spec.containers[:1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
-          echo ::set-output name=operator_image_tag::$(kubectl get deployment testkube-operator-controller-manager -o=jsonpath='{$.spec.template.spec.containers[1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
-          echo ::set-output name=dashboard_image_tag::$(kubectl get deployment testkube-dashboard -o=jsonpath='{$.spec.template.spec.containers[:1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
+  #     - name: Get image tag of Testkube APi, Dashboard, Operator
+  #       id: vars
+  #       run: |
+  #         echo ::set-output name=api_image_tag::$(kubectl get deployment testkube-api-server -o=jsonpath='{$.spec.template.spec.containers[:1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
+  #         echo ::set-output name=operator_image_tag::$(kubectl get deployment testkube-operator-controller-manager -o=jsonpath='{$.spec.template.spec.containers[1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
+  #         echo ::set-output name=dashboard_image_tag::$(kubectl get deployment testkube-dashboard -o=jsonpath='{$.spec.template.spec.containers[:1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
 
-      - name: Deploy if Executors' image is update
-        if: ${{ github.event.client_payload.image_tag_executor }}
-        run: |
-          helm dependency update ./charts/testkube
-          helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml  --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }} --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }}
+  #     - name: Deploy if Executors' image is update
+  #       if: ${{ github.event.client_payload.image_tag_executor }}
+  #       run: |
+  #         helm dependency update ./charts/testkube
+  #         helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml  --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }} --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }}
 
-      - name: Deploy if Testkube API image is updated
-        if: ${{ github.event.client_payload.image_tag }}
-        run: |
-          helm dependency update ./charts/testkube
-          helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-api.image.tag=${{ github.event.client_payload.image_tag }} --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }}
+  #     - name: Deploy if Testkube API image is updated
+  #       if: ${{ github.event.client_payload.image_tag }}
+  #       run: |
+  #         helm dependency update ./charts/testkube
+  #         helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-api.image.tag=${{ github.event.client_payload.image_tag }} --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }}
 
-      - name: Deploy if Testkube Dashboard image is updated
-        if: ${{ github.event.client_payload.image_tag_dashboard }}
-        run: |
-          helm dependency update ./charts/testkube
-          helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-dashboard.image.tag=${{ github.event.client_payload.image_tag_dashboard }} --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }}
+  #     - name: Deploy if Testkube Dashboard image is updated
+  #       if: ${{ github.event.client_payload.image_tag_dashboard }}
+  #       run: |
+  #         helm dependency update ./charts/testkube
+  #         helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-dashboard.image.tag=${{ github.event.client_payload.image_tag_dashboard }} --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }}
 
-      - name: Deploy if Testkube Operator image is updated
-        if: ${{ github.event.client_payload.image_tag_operator }}
-        run: |
-          helm dependency update ./charts/testkube
-          helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-operator.image.tag=${{ github.event.client_payload.image_tag_operator }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }} --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }}
+  #     - name: Deploy if Testkube Operator image is updated
+  #       if: ${{ github.event.client_payload.image_tag_operator }}
+  #       run: |
+  #         helm dependency update ./charts/testkube
+  #         helm upgrade --debug --install --atomic --timeout 180s ${{ env.DEPLOYMENT_NAME }} ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-operator.image.tag=${{ github.event.client_payload.image_tag_operator }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }} --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }}
 
-  notify_slack_if_deploy_stage_succeeds:
-    runs-on: ubuntu-latest
-    needs: release_charts_if_image_updated
-    steps:
-      - name: Slack Notification if the helm release deployment to ${{ env.ENV }} GKS succeeded.
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_CHANNEL: testkube-logs
-          SLACK_COLOR: ${{ needs.release_charts_if_image_updated.result }} # or a specific color like 'good' or '#ff00ff'
-          SLACK_ICON: https://github.com/rtCamp.png?size=48
-          SLACK_TITLE: Helm chart release successfully deployed into ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE :party_blob:!
-          SLACK_USERNAME: GitHub
-          SLACK_LINK_NAMES: true
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_FOOTER: "Kubeshop --> TestKube"
+  # notify_slack_if_deploy_stage_succeeds:
+  #   runs-on: ubuntu-latest
+  #   needs: release_charts_if_image_updated
+  #   steps:
+  #     - name: Slack Notification if the helm release deployment to ${{ env.ENV }} GKS succeeded.
+  #       uses: rtCamp/action-slack-notify@v2
+  #       env:
+  #         SLACK_CHANNEL: testkube-logs
+  #         SLACK_COLOR: ${{ needs.release_charts_if_image_updated.result }} # or a specific color like 'good' or '#ff00ff'
+  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
+  #         SLACK_TITLE: Helm chart release successfully deployed into ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE :party_blob:!
+  #         SLACK_USERNAME: GitHub
+  #         SLACK_LINK_NAMES: true
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         SLACK_FOOTER: "Kubeshop --> TestKube"
 
-  notify_slack_if_deploy_stage_failed:
-    runs-on: ubuntu-latest
-    needs: release_charts_if_image_updated
-    if: always() && (needs.release_charts_if_image_updated.result == 'failure')
-    steps:
-      - name: Slack Notification if the helm release deployment to ${{ env.ENV }} GKS failed.
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_CHANNEL: testkube-logs
-          SLACK_COLOR: ${{ needs.release_charts_if_image_updated.result }} # or a specific color like 'good' or '#ff00ff'
-          SLACK_ICON: https://github.com/rtCamp.png?size=48
-          SLACK_TITLE: Helm chart release failed to deploy into ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE! :boom:!
-          SLACK_USERNAME: GitHub
-          SLACK_LINK_NAMES: true
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_FOOTER: "Kubeshop --> TestKube"
+  # notify_slack_if_deploy_stage_failed:
+  #   runs-on: ubuntu-latest
+  #   needs: release_charts_if_image_updated
+  #   if: always() && (needs.release_charts_if_image_updated.result == 'failure')
+  #   steps:
+  #     - name: Slack Notification if the helm release deployment to ${{ env.ENV }} GKS failed.
+  #       uses: rtCamp/action-slack-notify@v2
+  #       env:
+  #         SLACK_CHANNEL: testkube-logs
+  #         SLACK_COLOR: ${{ needs.release_charts_if_image_updated.result }} # or a specific color like 'good' or '#ff00ff'
+  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
+  #         SLACK_TITLE: Helm chart release failed to deploy into ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE! :boom:!
+  #         SLACK_USERNAME: GitHub
+  #         SLACK_LINK_NAMES: true
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         SLACK_FOOTER: "Kubeshop --> TestKube"
 
   test_suite_run_stage:
     name: test suite for GKE cluster
     runs-on: ubuntu-latest
-    needs: release_charts_if_image_updated
+    # needs: release_charts_if_image_updated
     steps:
       # Setup gcloud CLI
       - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
@@ -151,6 +155,11 @@ jobs:
           cluster_name: ${{ env.GKE_CLUSTER_NAME_STAGE }}
           location: ${{ env.GKE_ZONE_STAGE }}
           credentials: ${{ secrets.GKE_SA_KEY }}
+      - name: Checkout tests from main Testkube repo
+        uses: actions/checkout@master
+        with:
+          repository: kubeshop/testkube
+          path: testkube
 
       # Runnning test suite
       - name: Run test suite
@@ -171,35 +180,35 @@ jobs:
           kubectl testkube create test -f ./${{ env.POSTMAN_TEST_FILE_NANE }} --name sanity --type postman/collection -v api_uri=http://testkube-api-server:8088 -v test_api_uri=http://testkube-api-server:8088 -v test_type=postman/collection -v test_name=fill-me -v execution_name=fill-me
           kubectl testkube run test sanity -f
 
-  notify_slack_if_test_suite_stage_succeeds:
-    runs-on: ubuntu-latest
-    needs: test_suite_run_stage
-    steps:
-      - name: Slack Notification if the test suite run on STAGE GKS succeeded.
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_CHANNEL: testkube-logs
-          SLACK_COLOR: ${{ needs.test_suite_run_stage.result }} # or a specific color like 'good' or '#ff00ff'
-          SLACK_ICON: https://github.com/rtCamp.png?size=48
-          SLACK_TITLE: Test suite successfully run against ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE :party_blob:!
-          SLACK_USERNAME: GitHub
-          SLACK_LINK_NAMES: true
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_FOOTER: "Kubeshop --> TestKube"
+  # notify_slack_if_test_suite_stage_succeeds:
+  #   runs-on: ubuntu-latest
+  #   needs: test_suite_run_stage
+  #   steps:
+  #     - name: Slack Notification if the test suite run on STAGE GKS succeeded.
+  #       uses: rtCamp/action-slack-notify@v2
+  #       env:
+  #         SLACK_CHANNEL: testkube-logs
+  #         SLACK_COLOR: ${{ needs.test_suite_run_stage.result }} # or a specific color like 'good' or '#ff00ff'
+  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
+  #         SLACK_TITLE: Test suite successfully run against ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE :party_blob:!
+  #         SLACK_USERNAME: GitHub
+  #         SLACK_LINK_NAMES: true
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         SLACK_FOOTER: "Kubeshop --> TestKube"
 
-  notify_slack_if_test_suite_failed:
-    runs-on: ubuntu-latest
-    needs: test_suite_run_stage
-    if: always() && (needs.test_suite_run_stage.result == 'failure')
-    steps:
-      - name: Slack Notification if the test suite run on ${{ env.ENV }} GKS failed.
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_CHANNEL: testkube-logs
-          SLACK_COLOR: ${{ needs.test_suite_run_stage.result }} # or a specific color like 'good' or '#ff00ff'
-          SLACK_ICON: https://github.com/rtCamp.png?size=48
-          SLACK_TITLE: Test suite FAILED to run on ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE! :boom:!
-          SLACK_USERNAME: GitHub
-          SLACK_LINK_NAMES: true
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_FOOTER: "Kubeshop --> TestKube"
+  # notify_slack_if_test_suite_failed:
+  #   runs-on: ubuntu-latest
+  #   needs: test_suite_run_stage
+  #   if: always() && (needs.test_suite_run_stage.result == 'failure')
+  #   steps:
+  #     - name: Slack Notification if the test suite run on ${{ env.ENV }} GKS failed.
+  #       uses: rtCamp/action-slack-notify@v2
+  #       env:
+  #         SLACK_CHANNEL: testkube-logs
+  #         SLACK_COLOR: ${{ needs.test_suite_run_stage.result }} # or a specific color like 'good' or '#ff00ff'
+  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
+  #         SLACK_TITLE: Test suite FAILED to run on ${{ secrets.GKE_CLUSTER_NAME_STAGE }} GKE! :boom:!
+  #         SLACK_USERNAME: GitHub
+  #         SLACK_LINK_NAMES: true
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         SLACK_FOOTER: "Kubeshop --> TestKube"
